# fly.toml app configuration file generated for pipetoresend on 2023-10-30T02:01:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pipetoresend"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
